---
title: "M3B_Covariates_Forward_Comparison"
author: "Yizhen Lai"
date: "2026-08-07"
output: html_document
---

```{r}
############################################################
# PopPK Fitting Control
# bobyqa + optExpression FALSE + single thread
############################################################

# Single-thread setting
rxode2::setRxThreads(1)

cat("rxode2 threads:", rxode2::getRxThreads(), "\n")


# Common PopPK fitting control
popPK_control <- nlmixr2est::foceiControl(
  outerOpt = "bobyqa",
  optExpression = FALSE
)

```

```{r}
############################################################
# M3B-1. Covariate Data Preparation
############################################################

library(dplyr)
library(readr)
library(here)

# ----------------------------------------------------------
# 1. Read cleaned PopPK dataset
# ----------------------------------------------------------

M3_data <- read_csv(
  here("Data", "warfarin_full_dataset_ID9_cleaned_for_popPKPD.csv"),
  show_col_types = FALSE
)


# ----------------------------------------------------------
# 2. Clean covariates
# ----------------------------------------------------------

M3_data <- M3_data %>%
  mutate(
    wt  = as.numeric(wt),
    age = as.numeric(age),

    # Standardize SEX text first
    sex = tolower(trimws(as.character(sex)))
  )


# Check SEX values before converting to factor
unique(M3_data$sex)

# ----------------------------------------------------------
# 3. Define SEX as a categorical variable
#    female = reference
# ----------------------------------------------------------

M3_data <- M3_data %>%
  mutate(
    sex = factor(
      sex,
      levels = c("female", "male")
    )
  )

levels(M3_data$sex)
table(M3_data$sex, useNA = "ifany")

# ----------------------------------------------------------
# 4. One record per subject
# ----------------------------------------------------------

cov_subject <- M3_data %>%
  select(id, wt, age, sex) %>%
  distinct() %>%
  arrange(id)

cov_subject

# Each subject should have only one set of baseline covariates
cov_subject %>%
  count(id) %>%
  filter(n > 1)

# ----------------------------------------------------------
# 5. Reference values
# ----------------------------------------------------------

# Continuous covariates:
# subject-level median as reference
wt_ref  <- median(cov_subject$wt,  na.rm = TRUE)
age_ref <- median(cov_subject$age, na.rm = TRUE)

# Categorical covariate:
# first factor level = reference
sex_ref <- levels(cov_subject$sex)[1]

wt_ref
age_ref
sex_ref

# ----------------------------------------------------------
# 6. Create model-ready covariates
# ----------------------------------------------------------

M3_data <- M3_data %>%
  mutate(

    # Continuous covariates centered on reference
    wt_ratio  = wt / wt_ref,
    age_ratio = age / age_ref,

    # Numeric contrast derived from the factor:
    # female = 0
    # male   = 1
    sex_male = as.integer(sex == "male")
  )

# ----------------------------------------------------------
# 7. Final QC
# ----------------------------------------------------------

wt_ref
age_ref
sex_ref

summary(M3_data$wt_ratio)
summary(M3_data$age_ratio)

table(M3_data$sex, useNA = "ifany")
table(M3_data$sex_male, useNA = "ifany")

```

```{r}
############################################################
# M3B-2. M3 base model
# M2 MUST BE RAN BEFORE THIS SECTION
############################################################

# Model specification
M3_base <- M2_full_IIV

# Use the already selected and converged M2 full-IIV fit
fit_M3_base <- fit_M2_full_IIV

```

```{r}
############################################################
# M3B-3. M3 base model + Body Weight on V/F
############################################################

M3_WT_V <- function() {
  ini({
    tka <- log(1)
    tcl <- log(0.145)
    tv  <- log(8.882)
    
    # initial value for Body Weight theta on V/F
    theta_wt_v <- 0 

    eta.ka ~ 0.1
    eta.cl ~ 0.1
    eta.v  ~ 0.1

    add.err  <- 0.3
    prop.err <- 0.2
  })

  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    
    # Body weight on V/F
    v <- exp(tv + theta_wt_v * log(wt_ratio) + eta.v) 


    d/dt(depot)   = -ka * depot
    d/dt(central) =  ka * depot - cl / v * central

    cp = central / v

    cp ~ add(add.err) + prop(prop.err)
  })
}


# ----------------------------------------------------------
# Fit the Model
# ----------------------------------------------------------

fit_M3_WT_V <- nlmixr2(
  M3_base,
  data = M3_data,
  est = "focei",
  control = popPK_control
)

```

```{r}
############################################################
# M3B-4. M3 base model + Body Weight and Sex on V/F
############################################################

M3_WT_V_SEX_V <- function() {
  ini({
    tka <- log(1)
    tcl <- log(0.145)
    tv  <- log(8.882)
    
    # initial value for Body Weight theta on V/F
    theta_wt_v <- 0 
    
    # initial value for Sex theta on V/F
    theta_sex_v <- 0

    eta.ka ~ 0.1
    eta.cl ~ 0.1
    eta.v  ~ 0.1

    add.err  <- 0.3
    prop.err <- 0.2
  })

  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    
    # Sex on Body Weight_V backbone
    v <- exp(tv + theta_wt_v * log(wt_ratio) + theta_sex_v * sex_male + eta.v) 


    d/dt(depot)   = -ka * depot
    d/dt(central) =  ka * depot - cl / v * central

    cp = central / v

    cp ~ add(add.err) + prop(prop.err)
  })
}


# ----------------------------------------------------------
# Fit the Model
# ----------------------------------------------------------

fit_M3_WT_V_SEX_V <- nlmixr2(
  M3_WT_V_SEX_V,
  data = M3_data,
  est = "focei",
  control = popPK_control
)
```

```{r}
############################################################
# M3B-5. M3 base model + Body Weight on CL/F
############################################################

M3_WT_CL <- function() {
  ini({
    tka <- log(1)
    tcl <- log(0.145)
    tv  <- log(8.882)
    
    # initial value for Body Weight theta on CL/F
    theta_wt_cl <- 0 

    eta.ka ~ 0.1
    eta.cl ~ 0.1
    eta.v  ~ 0.1

    add.err  <- 0.3
    prop.err <- 0.2
  })

  model({
    ka <- exp(tka + eta.ka)
    
    # Body Weight on CL/F
    cl <- exp(tcl + theta_wt_cl * log(wt_ratio) + eta.cl)
  
    v <- exp(tv + eta.v) 


    d/dt(depot)   = -ka * depot
    d/dt(central) =  ka * depot - cl / v * central

    cp = central / v

    cp ~ add(add.err) + prop(prop.err)
  })
}


# ----------------------------------------------------------
# Fit the Model
# ----------------------------------------------------------

fit_M3_WT_CL <- nlmixr2(
  M3_WT_CL,
  data = M3_data,
  est = "focei",
  control = popPK_control
)

```

```{r}

############################################################
# M3B-6. M3 base model + Body Weight on CL/F and V/F
############################################################

M3_WT_CL_V <- function() {
  ini({
    tka <- log(1)
    tcl <- log(0.145)
    tv  <- log(8.882)

    # initial value for Body Weight theta on CL/F
    theta_wt_cl <- 0
    
    # initial value for Body Weight theta on V/F
    theta_wt_v  <- 0

    eta.ka ~ 0.1
    eta.cl ~ 0.1
    eta.v  ~ 0.1

    add.err  <- 0.3
    prop.err <- 0.2
  })

  model({
    ka <- exp(tka + eta.ka)

    # Body Weight on CL/F
    cl <- exp(tcl + theta_wt_cl * log(wt_ratio) + eta.cl)

    # Body Weight on V/F
    v <- exp(tv + theta_wt_v * log(wt_ratio) + eta.v)

    d/dt(depot)   = -ka * depot
    d/dt(central) =  ka * depot - cl / v * central

    cp = central / v

    cp ~ add(add.err) + prop(prop.err)
  })
}


# ----------------------------------------------------------
# Fit the Model
# ----------------------------------------------------------

fit_M3_WT_CL_V <- nlmixr2(
  M3_WT_CL_V,
  data = M3_data,
  est = "focei",
  control = popPK_control
)

```

```{r}
############################################################
# M3B-7*. AGE on CL/F (cold start)
############################################################

M3_AGE_CL <- function() {
  ini({
    tka <- log(1)
    tcl <- log(0.145)
    tv  <- log(8.882)

    # initial value for Age theta on CL/F
    theta_age_cl <- 0

    eta.ka ~ 0.1
    eta.cl ~ 0.1
    eta.v  ~ 0.1

    add.err  <- 0.3
    prop.err <- 0.2
  })

  model({
    ka <- exp(tka + eta.ka)

    # Age on CL/F
    cl <- exp(tcl + theta_age_cl * log(age_ratio) + eta.cl)

    v <- exp(tv + eta.v)

    d/dt(depot)   = -ka * depot
    d/dt(central) = ka * depot - cl / v * central

    cp = central / v

    cp ~ add(add.err) + prop(prop.err)
  })
}


# ----------------------------------------------------------
# Fit M3 AGE on CL/F model
# ----------------------------------------------------------

fit_M3_AGE_CL <- nlmixr2(
  M3_AGE_CL,
  data = M3_data,
  est = "focei",
  control = popPK_control
)



```

```{r}
library(nlmixr2)
library(magrittr)

############################################################
# Warm-start M3_AGE_CL from converged M3_base
############################################################

M3_AGE_CL_warm <- fit_M3_base %>%

  # Only modify the CL equation
  model({
    cl <- exp(
      tcl +
      theta_age_cl * log(age_ratio) +
      eta.cl
    )
  }) %>%

  # Only the NEW covariate parameter starts from 0
  ini(
    theta_age_cl = 0
  )


############################################################
# Fit warm-start AGE -> CL model
############################################################

fit_M3_AGE_CL_warm <- nlmixr2(
  M3_AGE_CL_warm,
  data = M3_data,
  est = "focei",
  control = popPK_control
)

```

```{r}

############################################################
# M3B-8. Body Weight on CL/F and V/F + Age on CL/F
############################################################

M3_WT_CL_V_AGE_CL <- function() {
  ini({
    tka <- log(1)
    tcl <- log(0.145)
    tv  <- log(8.882)

    # initial value for the selected covariates
    theta_wt_cl  <- 0
    theta_wt_v   <- 0
    theta_age_cl <- 0

    eta.ka ~ 0.1
    eta.cl ~ 0.1
    eta.v  ~ 0.1

    add.err  <- 0.3
    prop.err <- 0.2
  })

  model({
    ka <- exp(tka + eta.ka)

    # Body Weight + Age on CL/F
    cl <- exp(
      tcl +
      theta_wt_cl  * log(wt_ratio) +
      theta_age_cl * log(age_ratio) +
      eta.cl
    )

    # Body Weight on V/F
    v <- exp(
      tv +
      theta_wt_v * log(wt_ratio) +
      eta.v
    )

    d/dt(depot)   = -ka * depot
    d/dt(central) =  ka * depot - cl / v * central

    cp = central / v

    cp ~ add(add.err) + prop(prop.err)
  })
}


# ----------------------------------------------------------
# Fit the Model
# ----------------------------------------------------------

fit_M3_WT_CL_V_AGE_CL <- nlmixr2(
  M3_WT_CL_V_AGE_CL,
  data = M3_data,
  est = "focei",
  control = popPK_control
)

```

```{r}
############################################################
# M3B-9. Candidate Full Covariate Model
# WT on CL/F and V/F
# AGE on CL/F
# SEX on V/F
############################################################

M3_candidate_full <- function() {
  ini({
    tka <- log(1)
    tcl <- log(0.145)
    tv  <- log(8.882)

    # initial value for the selected covariates
    theta_wt_cl  <- 0
    theta_wt_v   <- 0
    theta_age_cl <- 0
    theta_sex_v  <- 0

    eta.ka ~ 0.1
    eta.cl ~ 0.1
    eta.v  ~ 0.1

    add.err  <- 0.3
    prop.err <- 0.2
  })

  model({
    ka <- exp(tka + eta.ka)

    # WT + AGE on CL/F
    cl <- exp(
      tcl +
      theta_wt_cl  * log(wt_ratio) +
      theta_age_cl * log(age_ratio) +
      eta.cl
    )

    # WT + SEX on V/F
    v <- exp(
      tv +
      theta_wt_v  * log(wt_ratio) +
      theta_sex_v * sex_male +
      eta.v
    )

    d/dt(depot)   = -ka * depot
    d/dt(central) = ka * depot - cl / v * central

    cp = central / v

    cp ~ add(add.err) + prop(prop.err)
  })
}


# ----------------------------------------------------------
# Fit Candidate Full Model
# ----------------------------------------------------------

fit_M3_candidate_full <- nlmixr2(
  M3_candidate_full,
  data = M3_data,
  est = "focei",
  control = popPK_control
)

```